// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class HandEquity {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HandEquity {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHandEquity(bb:flatbuffers.ByteBuffer, obj?:HandEquity):HandEquity {
  return (obj || new HandEquity()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHandEquity(bb:flatbuffers.ByteBuffer, obj?:HandEquity):HandEquity {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HandEquity()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

handName():string|null
handName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
handName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

equity():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

wins():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

ties():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

losses():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

simulations():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

winMethodMatrix(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

winMethodMatrixLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

winMethodMatrixArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

lossMethodMatrix(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

lossMethodMatrixLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

lossMethodMatrixArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startHandEquity(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addHandName(builder:flatbuffers.Builder, handNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, handNameOffset, 0);
}

static addEquity(builder:flatbuffers.Builder, equity:number) {
  builder.addFieldFloat64(1, equity, 0.0);
}

static addWins(builder:flatbuffers.Builder, wins:number) {
  builder.addFieldInt32(2, wins, 0);
}

static addTies(builder:flatbuffers.Builder, ties:number) {
  builder.addFieldInt32(3, ties, 0);
}

static addLosses(builder:flatbuffers.Builder, losses:number) {
  builder.addFieldInt32(4, losses, 0);
}

static addSimulations(builder:flatbuffers.Builder, simulations:number) {
  builder.addFieldInt32(5, simulations, 0);
}

static addWinMethodMatrix(builder:flatbuffers.Builder, winMethodMatrixOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, winMethodMatrixOffset, 0);
}

static createWinMethodMatrixVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createWinMethodMatrixVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createWinMethodMatrixVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startWinMethodMatrixVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLossMethodMatrix(builder:flatbuffers.Builder, lossMethodMatrixOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, lossMethodMatrixOffset, 0);
}

static createLossMethodMatrixVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createLossMethodMatrixVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createLossMethodMatrixVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startLossMethodMatrixVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endHandEquity(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHandEquity(builder:flatbuffers.Builder, handNameOffset:flatbuffers.Offset, equity:number, wins:number, ties:number, losses:number, simulations:number, winMethodMatrixOffset:flatbuffers.Offset, lossMethodMatrixOffset:flatbuffers.Offset):flatbuffers.Offset {
  HandEquity.startHandEquity(builder);
  HandEquity.addHandName(builder, handNameOffset);
  HandEquity.addEquity(builder, equity);
  HandEquity.addWins(builder, wins);
  HandEquity.addTies(builder, ties);
  HandEquity.addLosses(builder, losses);
  HandEquity.addSimulations(builder, simulations);
  HandEquity.addWinMethodMatrix(builder, winMethodMatrixOffset);
  HandEquity.addLossMethodMatrix(builder, lossMethodMatrixOffset);
  return HandEquity.endHandEquity(builder);
}
}
