// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EvolutionPath {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EvolutionPath {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEvolutionPath(bb:flatbuffers.ByteBuffer, obj?:EvolutionPath):EvolutionPath {
  return (obj || new EvolutionPath()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEvolutionPath(bb:flatbuffers.ByteBuffer, obj?:EvolutionPath):EvolutionPath {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EvolutionPath()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pathString():string|null
pathString(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
pathString(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

count():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startEvolutionPath(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPathString(builder:flatbuffers.Builder, pathStringOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pathStringOffset, 0);
}

static addCount(builder:flatbuffers.Builder, count:number) {
  builder.addFieldInt32(1, count, 0);
}

static endEvolutionPath(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEvolutionPath(builder:flatbuffers.Builder, pathStringOffset:flatbuffers.Offset, count:number):flatbuffers.Offset {
  EvolutionPath.startEvolutionPath(builder);
  EvolutionPath.addPathString(builder, pathStringOffset);
  EvolutionPath.addCount(builder, count);
  return EvolutionPath.endEvolutionPath(builder);
}
}
