// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class HandEquity {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HandEquity {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHandEquity(bb:flatbuffers.ByteBuffer, obj?:HandEquity):HandEquity {
  return (obj || new HandEquity()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHandEquity(bb:flatbuffers.ByteBuffer, obj?:HandEquity):HandEquity {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HandEquity()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

handName():string|null
handName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
handName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

equity():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

wins():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

ties():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

losses():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

simulations():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startHandEquity(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addHandName(builder:flatbuffers.Builder, handNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, handNameOffset, 0);
}

static addEquity(builder:flatbuffers.Builder, equity:number) {
  builder.addFieldFloat64(1, equity, 0.0);
}

static addWins(builder:flatbuffers.Builder, wins:number) {
  builder.addFieldInt32(2, wins, 0);
}

static addTies(builder:flatbuffers.Builder, ties:number) {
  builder.addFieldInt32(3, ties, 0);
}

static addLosses(builder:flatbuffers.Builder, losses:number) {
  builder.addFieldInt32(4, losses, 0);
}

static addSimulations(builder:flatbuffers.Builder, simulations:number) {
  builder.addFieldInt32(5, simulations, 0);
}

static endHandEquity(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHandEquity(builder:flatbuffers.Builder, handNameOffset:flatbuffers.Offset, equity:number, wins:number, ties:number, losses:number, simulations:number):flatbuffers.Offset {
  HandEquity.startHandEquity(builder);
  HandEquity.addHandName(builder, handNameOffset);
  HandEquity.addEquity(builder, equity);
  HandEquity.addWins(builder, wins);
  HandEquity.addTies(builder, ties);
  HandEquity.addLosses(builder, losses);
  HandEquity.addSimulations(builder, simulations);
  return HandEquity.endHandEquity(builder);
}
}
