// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { HandEquity } from '../telemetry/hand-equity.js';


export class TelemetryPacket {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TelemetryPacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTelemetryPacket(bb:flatbuffers.ByteBuffer, obj?:TelemetryPacket):TelemetryPacket {
  return (obj || new TelemetryPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTelemetryPacket(bb:flatbuffers.ByteBuffer, obj?:TelemetryPacket):TelemetryPacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TelemetryPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestampNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

jobStartNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

handsProcessed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

cpuPercent():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

memoryRssKb():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

memoryVmsKb():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

threadCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

cpuCycles():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

status():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

equityResults(index: number, obj?:HandEquity):HandEquity|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new HandEquity()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

equityResultsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTelemetryPacket(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addTimestampNs(builder:flatbuffers.Builder, timestampNs:bigint) {
  builder.addFieldInt64(0, timestampNs, BigInt('0'));
}

static addJobStartNs(builder:flatbuffers.Builder, jobStartNs:bigint) {
  builder.addFieldInt64(1, jobStartNs, BigInt('0'));
}

static addHandsProcessed(builder:flatbuffers.Builder, handsProcessed:bigint) {
  builder.addFieldInt64(2, handsProcessed, BigInt('0'));
}

static addCpuPercent(builder:flatbuffers.Builder, cpuPercent:number) {
  builder.addFieldFloat64(3, cpuPercent, 0.0);
}

static addMemoryRssKb(builder:flatbuffers.Builder, memoryRssKb:bigint) {
  builder.addFieldInt64(4, memoryRssKb, BigInt('0'));
}

static addMemoryVmsKb(builder:flatbuffers.Builder, memoryVmsKb:bigint) {
  builder.addFieldInt64(5, memoryVmsKb, BigInt('0'));
}

static addThreadCount(builder:flatbuffers.Builder, threadCount:number) {
  builder.addFieldInt32(6, threadCount, 0);
}

static addCpuCycles(builder:flatbuffers.Builder, cpuCycles:bigint) {
  builder.addFieldInt64(7, cpuCycles, BigInt('0'));
}

static addStatus(builder:flatbuffers.Builder, status:number) {
  builder.addFieldInt8(8, status, 0);
}

static addEquityResults(builder:flatbuffers.Builder, equityResultsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, equityResultsOffset, 0);
}

static createEquityResultsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEquityResultsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTelemetryPacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTelemetryPacketBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedTelemetryPacketBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createTelemetryPacket(builder:flatbuffers.Builder, timestampNs:bigint, jobStartNs:bigint, handsProcessed:bigint, cpuPercent:number, memoryRssKb:bigint, memoryVmsKb:bigint, threadCount:number, cpuCycles:bigint, status:number, equityResultsOffset:flatbuffers.Offset):flatbuffers.Offset {
  TelemetryPacket.startTelemetryPacket(builder);
  TelemetryPacket.addTimestampNs(builder, timestampNs);
  TelemetryPacket.addJobStartNs(builder, jobStartNs);
  TelemetryPacket.addHandsProcessed(builder, handsProcessed);
  TelemetryPacket.addCpuPercent(builder, cpuPercent);
  TelemetryPacket.addMemoryRssKb(builder, memoryRssKb);
  TelemetryPacket.addMemoryVmsKb(builder, memoryVmsKb);
  TelemetryPacket.addThreadCount(builder, threadCount);
  TelemetryPacket.addCpuCycles(builder, cpuCycles);
  TelemetryPacket.addStatus(builder, status);
  TelemetryPacket.addEquityResults(builder, equityResultsOffset);
  return TelemetryPacket.endTelemetryPacket(builder);
}
}
